### PR TITLE
Add exclude unchanged to release step

### PR DESCRIPTION
**Pull request by rlebran**

### CODE REVIEW

**Comment by Xerxes004** [comment]
Any chance of getting this merged at some point?

**Comment by epage** [comment]
- This PR has conflicts
- This PR was posted without respect to any of the conversation at #298.  We should resolve on a solution there before moving onto a PR per our [CONTRIBUTING.md](https://github.com/crate-ci/cargo-release/blob/master/CONTRIBUTING.md#pull-requests)

I'm going to close this until we've finished discussing the design.

**Comment by rlebran** [comment]
Hi,
Just for you information, we use it for a while at my current company and it sometime works well and sometime isn't enough.
This would be a nice change for this project in the future and I just wanted to use what already existing but this was not ready to be merged. This PR shouldn't have been open, sorry for the noise !

**Comment by Xerxes004** [comment]
Good stuff, thanks all.

**Pull request closed without merging**
